from PyQt5.QtWidgets import QProgressBar, QComboBox, QSpinBox, QTreeWidgetItem, QDoubleSpinBox, QHBoxLayout, QLineEdit, \
    QPushButton, QWidget, QSizePolicy, QLabel

from ui.appui1 import Ui_MainWindow


class MainWindow_UI(Ui_MainWindow):
    def setup(self, MainWindow):
        self.setupUi(MainWindow)
        self.splitter_Left.setStretchFactor(1, 1)
        self.splitter_Right.setStretchFactor(0, 1)

        # statusbar
        self.label_statubar = QLabel()
        self.label_statubar.setText('Ready')
        self.statusbar.addWidget(self.label_statubar)
        self.progressBar_statubar = QProgressBar()
        self.progressBar_statubar.setValue(0)
        self.statusbar.addWidget(self.progressBar_statubar)

        # graphshow_Main
        self.horizontalLayout_imageview.setStretch(0, 1)
        self.horizontalLayout_imageview.setStretch(1, 1)
        self.horizontalLayout_imageview.setStretch(2, 1)
        self.graphicsView_Main2.setVisible(False)
        self.graphicsView_Main3.setVisible(False)
        self.pushButton_Paint.setVisible(False)
        self.pushButton_Erase.setVisible(False)
        self.pushButton_Mask.setVisible(False)

        # tab_Postprocess
        self.comboBox_Method.setEnabled(False)
        self.doubleSpinBox_Threshold.setEnabled(False)
        self.spinBox_Dilation = QSpinBox()
        self.spinBox_AreaThreshold = QSpinBox()
        self.spinBox_rbo_Left = QSpinBox()
        self.spinBox_rbo_Right = QSpinBox()
        self.spinBox_rbo_Top = QSpinBox()
        self.spinBox_rbo_Bottom = QSpinBox()
        self.pushButton_Inpainting = QPushButton('Inpainting')
        self.spinBox_AutoInpainting = QSpinBox()
        self.trWItem_rso = self.treeWidget_ProcessingConfig.topLevelItem(0)
        self.trWItem_rbo = self.treeWidget_ProcessingConfig.topLevelItem(1)
        self.treeWidget_ProcessingConfig.setItemWidget(self.trWItem_rso.child(0), 1, self.spinBox_Dilation)
        self.treeWidget_ProcessingConfig.setItemWidget(self.trWItem_rso.child(1), 1, self.spinBox_AreaThreshold)
        self.treeWidget_ProcessingConfig.setItemWidget(self.trWItem_rbo.child(0), 1, self.spinBox_rbo_Left)
        self.treeWidget_ProcessingConfig.setItemWidget(self.trWItem_rbo.child(1), 1, self.spinBox_rbo_Top)
        self.treeWidget_ProcessingConfig.setItemWidget(self.trWItem_rbo.child(2), 1, self.spinBox_rbo_Right)
        self.treeWidget_ProcessingConfig.setItemWidget(self.trWItem_rbo.child(3), 1, self.spinBox_rbo_Bottom)
        self.treeWidget_ProcessingConfig.setItemWidget(self.treeWidget_ProcessingConfig.topLevelItem(2).child(0), 1,
                                                       self.pushButton_Inpainting)
        self.treeWidget_ProcessingConfig.setItemWidget(self.treeWidget_ProcessingConfig.topLevelItem(2).child(1), 1,
                                                       self.spinBox_AutoInpainting)

        # tab_calculate
        self.trWItem_area = self.treeWidget_Traits.topLevelItem(0)
        self.trWItem_convex_area = self.treeWidget_Traits.topLevelItem(1)
        self.trWItem_length = self.treeWidget_Traits.topLevelItem(2)
        self.trWItem_diameter = self.treeWidget_Traits.topLevelItem(3)
        self.trWItem_depth = self.treeWidget_Traits.topLevelItem(4)
        self.trWItem_width = self.treeWidget_Traits.topLevelItem(5)
        self.trWItem_wdRatio = self.treeWidget_Traits.topLevelItem(6)
        self.trWItem_sturdiness = self.treeWidget_Traits.topLevelItem(7)
        self.trWItem_initial_x = self.treeWidget_Traits.topLevelItem(8)
        self.trWItem_initial_y = self.treeWidget_Traits.topLevelItem(9)
        self.trWItem_centroid_x = self.treeWidget_Traits.topLevelItem(10)
        self.trWItem_centroid_y = self.treeWidget_Traits.topLevelItem(11)
        self.trWItem_angle_apex_left = self.treeWidget_Traits.topLevelItem(12)
        self.trWItem_angle_apex_right = self.treeWidget_Traits.topLevelItem(13)
        self.trWItem_angle_apex_all = self.treeWidget_Traits.topLevelItem(14)
        self.trWItem_angle_entire_left = self.treeWidget_Traits.topLevelItem(15)
        self.trWItem_angle_entire_right = self.treeWidget_Traits.topLevelItem(16)
        self.trWItem_angle_entire_all = self.treeWidget_Traits.topLevelItem(17)
        self.trWItem_layer_mass = self.treeWidget_Traits.topLevelItem(18)
        self.trWItem_layer_mass.setExpanded(True)
        self.trWItem_lmchild_Area = self.trWItem_layer_mass.child(0)
        self.trWItem_lmchild_Length = self.trWItem_layer_mass.child(1)
        self.trWItem_lmchild_Convex_hull = self.trWItem_layer_mass.child(2)
        self.trWItem_lmchild_A_C = self.trWItem_layer_mass.child(3)
        self.trWItem_lmchild_A_L = self.trWItem_layer_mass.child(4)
        self.trWItem_lmchild_L_C = self.trWItem_layer_mass.child(5)

        # tab_Train
        self.treewidgetitem_model = QTreeWidgetItem(self.treeWidget_Train)
        self.comboBox_TrainableModel = QComboBox()
        self.treeWidget_Train.setItemWidget(self.treewidgetitem_model, 1, self.comboBox_TrainableModel)
        self.treewidgetitem_iters = QTreeWidgetItem(self.treeWidget_Train)
        self.spinBox_Iters = QSpinBox()
        self.treeWidget_Train.setItemWidget(self.treewidgetitem_iters, 1, self.spinBox_Iters)
        self.treewidgetitem_batchsize = QTreeWidgetItem(self.treeWidget_Train)
        self.spinBox_BatchSize = QSpinBox()
        self.treeWidget_Train.setItemWidget(self.treewidgetitem_batchsize, 1, self.spinBox_BatchSize)
        self.treewidgetitem_lr = QTreeWidgetItem(self.treeWidget_Train)
        self.doubleSpinBox_Lr = QDoubleSpinBox()
        self.treeWidget_Train.setItemWidget(self.treewidgetitem_lr, 1, self.doubleSpinBox_Lr)
        self.treeWidgetItem_datsetpath = QTreeWidgetItem(self.treeWidget_Train)
        self.horizontalLayout_DatasetPath = QHBoxLayout()
        self.lineEdit_DatasetPath = QLineEdit()
        self.pushButton_DatasetPath = QPushButton(' . . . ')
        self.horizontalLayout_DatasetPath.addWidget(self.lineEdit_DatasetPath)
        self.horizontalLayout_DatasetPath.addWidget(self.pushButton_DatasetPath)
        self.widget_DatsetPath = QWidget()
        self.widget_DatsetPath.setLayout(self.horizontalLayout_DatasetPath)
        self.treeWidget_Train.setItemWidget(self.treeWidgetItem_datsetpath, 1, self.widget_DatsetPath)
        self.treeWidgetItem_SaveDir = QTreeWidgetItem(self.treeWidget_Train)
        self.horizontalLayout_SaveDir = QHBoxLayout()
        self.lineEdit_SaveDir_train = QLineEdit()
        self.pushButton_SaveDir_train = QPushButton(' . . . ')
        self.horizontalLayout_SaveDir.addWidget(self.lineEdit_SaveDir_train)
        self.horizontalLayout_SaveDir.addWidget(self.pushButton_SaveDir_train)
        self.widget_SaveDir = QWidget()
        self.widget_SaveDir.setLayout(self.horizontalLayout_SaveDir)
        self.treeWidget_Train.setItemWidget(self.treeWidgetItem_SaveDir, 1, self.widget_SaveDir)
        self.treeWidgetItem_DatasetSplit = QTreeWidgetItem(self.treeWidget_Train)
        self.horizontalLayout_DatasetSplit = QHBoxLayout()
        self.doubleSpinBox_DatasetSplit_train = QDoubleSpinBox()
        self.doubleSpinBox_DatasetSplit_val = QDoubleSpinBox()
        self.horizontalLayout_DatasetSplit.addWidget(self.doubleSpinBox_DatasetSplit_train)
        self.horizontalLayout_DatasetSplit.addWidget(self.doubleSpinBox_DatasetSplit_val)
        self.widget_DatasetSplit = QWidget()
        self.widget_DatasetSplit.setLayout(self.horizontalLayout_DatasetSplit)
        self.treeWidget_Train.setItemWidget(self.treeWidgetItem_DatasetSplit, 1, self.widget_DatasetSplit)
        self.treeWidgetItem_ResumeModel = QTreeWidgetItem(self.treeWidget_Train)
        self.horizontalLayout_ResumeModel = QHBoxLayout()
        self.lineEdit_ResumeModel = QLineEdit()
        self.pushButton_ResumeModel = QPushButton(' . . . ')
        self.horizontalLayout_ResumeModel.addWidget(self.lineEdit_ResumeModel)
        self.horizontalLayout_ResumeModel.addWidget(self.pushButton_ResumeModel)
        self.widget_ResumeModel = QWidget()
        self.widget_ResumeModel.setLayout(self.horizontalLayout_ResumeModel)
        self.treeWidget_Train.setItemWidget(self.treeWidgetItem_ResumeModel, 1, self.widget_ResumeModel)
        self.treeWidgetItem_LogIters = QTreeWidgetItem(self.treeWidget_Train)
        self.spinBox_LogIters = QSpinBox()
        self.treeWidget_Train.setItemWidget(self.treeWidgetItem_LogIters, 1, self.spinBox_LogIters)
        self.treeWidgetItem_SaveInterval = QTreeWidgetItem(self.treeWidget_Train)
        self.spinBox_SaveInterval = QSpinBox()
        self.treeWidget_Train.setItemWidget(self.treeWidgetItem_SaveInterval, 1, self.spinBox_SaveInterval)
        self.treeWidgetItem_KeepCheckpointMax = QTreeWidgetItem(self.treeWidget_Train)
        self.spinBox_KeepCheckpointMax = QSpinBox()
        self.treeWidget_Train.setItemWidget(self.treeWidgetItem_KeepCheckpointMax, 1, self.spinBox_KeepCheckpointMax)
        self.treeWidgetItem_CropSize = QTreeWidgetItem(self.treeWidget_Train)
        self.spinBox_CropSize_train = QSpinBox()
        self.treeWidget_Train.setItemWidget(self.treeWidgetItem_CropSize, 1, self.spinBox_CropSize_train)

        self.setup_attribute()
        self.setup_default()

    def setup_attribute(self):
        # main
        self.splitter_Middle.setStretchFactor(1, 1)
        # tab_PostPreprocess
        self.spinBox_Dilation.setMaximum(999999999)
        self.spinBox_AreaThreshold.setMaximum(999999999)
        self.spinBox_rbo_Left.setMaximum(999999999)
        self.spinBox_rbo_Right.setMaximum(999999999)
        self.spinBox_rbo_Top.setMaximum(999999999)
        self.spinBox_rbo_Bottom.setMaximum(999999999)
        self.spinBox_AutoInpainting.setMaximum(999999999)

        # tab_Train
        self.spinBox_Iters.setMaximum(999999999)
        self.doubleSpinBox_Lr.setDecimals(6)
        self.doubleSpinBox_Lr.setSingleStep(0.000001)
        self.lineEdit_DatasetPath.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        # self.pushButton_DatasetPath.setMaximumSize(50, 16777215)
        self.horizontalLayout_DatasetPath.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_DatasetPath.setSpacing(0)
        self.lineEdit_SaveDir_train.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        # self.pushButton_SaveDir_train.setMaximumSize(50, 16777215)
        self.horizontalLayout_SaveDir.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_SaveDir.setSpacing(0)
        self.doubleSpinBox_DatasetSplit_train.setSingleStep(0.1)
        self.doubleSpinBox_DatasetSplit_train.setMaximum(1)
        self.doubleSpinBox_DatasetSplit_val.setSingleStep(0.1)
        self.doubleSpinBox_DatasetSplit_val.setMaximum(1)
        self.horizontalLayout_DatasetSplit.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_DatasetSplit.setSpacing(0)
        self.lineEdit_ResumeModel.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        # self.pushButton_ResumeModel.setMaximumSize(50, 16777215)
        self.horizontalLayout_ResumeModel.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_ResumeModel.setSpacing(0)
        self.spinBox_LogIters.setMaximum(999999999)
        self.spinBox_SaveInterval.setMaximum(999999999)
        self.spinBox_KeepCheckpointMax.setMaximum(999999999)
        self.spinBox_CropSize_train.setMaximum(9999)

    def setup_default(self):
        # tab_Calculate
        self.spinBox_LayerHeight.setValue(0)
        self.spinBox_LayerWidth.setValue(0)
        self.doubleSpinBox_LayerWidth.setVisible(False)
        self.doubleSpinBox_LayerHeight.setVisible(False)
        self.traits_init()
        # tab_Train
        self.treewidgetitem_model.setText(0, 'model_type')
        self.treewidgetitem_iters.setText(0, 'iters')
        self.spinBox_Iters.setValue(40000)
        self.treewidgetitem_batchsize.setText(0, 'batch_size')
        self.spinBox_BatchSize.setValue(1)
        self.treewidgetitem_lr.setText(0, 'learning_rate')
        self.doubleSpinBox_Lr.setValue(0.0002)
        self.treeWidgetItem_datsetpath.setText(0, 'dataset_path')
        self.treeWidgetItem_SaveDir.setText(0, 'save_dir')
        self.lineEdit_SaveDir_train.setText('output')
        self.treeWidgetItem_DatasetSplit.setText(0, 'dataset_split')
        self.doubleSpinBox_DatasetSplit_train.setValue(0.8)
        self.doubleSpinBox_DatasetSplit_val.setValue(0.2)
        self.treeWidgetItem_ResumeModel.setText(0, 'resume_model')
        self.treeWidgetItem_LogIters.setText(0, 'log_iters')
        self.spinBox_LogIters.setValue(10)
        self.treeWidgetItem_SaveInterval.setText(0, 'save_interval')
        self.spinBox_SaveInterval.setValue(1000)
        self.treeWidgetItem_KeepCheckpointMax.setText(0, 'keep_checkpoint_max')
        self.spinBox_KeepCheckpointMax.setValue(5)
        self.treeWidgetItem_CropSize.setText(0, 'crop_size')
        self.spinBox_CropSize_train.setValue(512)

    def traits_init(self):
        self.trWItem_area.setText(1, '0')
        self.trWItem_convex_area.setText(1, '0')
        self.trWItem_length.setText(1, '0')
        self.trWItem_diameter.setText(1, '0')
        self.trWItem_depth.setText(1, '0')
        self.trWItem_width.setText(1, '0')
        self.trWItem_wdRatio.setText(1, '0')
        self.trWItem_sturdiness.setText(1, '0')
        self.trWItem_initial_x.setText(1, '0')
        self.trWItem_initial_y.setText(1, '0')
        self.trWItem_centroid_x.setText(1, '0')
        self.trWItem_centroid_y.setText(1, '0')
        self.trWItem_angle_apex_left.setText(1, '0')
        self.trWItem_angle_apex_right.setText(1, '0')
        self.trWItem_angle_apex_all.setText(1, '0')
        self.trWItem_angle_entire_left.setText(1, '0')
        self.trWItem_angle_entire_right.setText(1, '0')
        self.trWItem_angle_entire_all.setText(1, '0')
        self.trWItem_lmchild_Area.setText(1, '[]')
        self.trWItem_lmchild_Convex_hull.setText(1, '[]')
        self.trWItem_lmchild_Length.setText(1, '[]')
        self.trWItem_lmchild_A_C.setText(1, '[]')
        self.trWItem_lmchild_A_L.setText(1, '[]')
        self.trWItem_lmchild_L_C.setText(1, '[]')

        self.trWItem_convex_area = self.treeWidget_Traits.topLevelItem(1)
        self.trWItem_length = self.treeWidget_Traits.topLevelItem(2)
        self.trWItem_diameter = self.treeWidget_Traits.topLevelItem(3)
        self.trWItem_depth = self.treeWidget_Traits.topLevelItem(4)
        self.trWItem_width = self.treeWidget_Traits.topLevelItem(5)
        self.trWItem_wdRatio = self.treeWidget_Traits.topLevelItem(6)
        self.trWItem_sturdiness = self.treeWidget_Traits.topLevelItem(7)
        self.trWItem_initial_x = self.treeWidget_Traits.topLevelItem(8)
        self.trWItem_initial_y = self.treeWidget_Traits.topLevelItem(9)
        self.trWItem_centroid_x = self.treeWidget_Traits.topLevelItem(10)
        self.trWItem_centroid_y = self.treeWidget_Traits.topLevelItem(11)
        self.trWItem_angle_apex_left = self.treeWidget_Traits.topLevelItem(12)
        self.trWItem_angle_apex_right = self.treeWidget_Traits.topLevelItem(13)
        self.trWItem_angle_apex_all = self.treeWidget_Traits.topLevelItem(14)
        self.trWItem_angle_entire_left = self.treeWidget_Traits.topLevelItem(15)
        self.trWItem_angle_entire_right = self.treeWidget_Traits.topLevelItem(16)
        self.trWItem_angle_entire_all = self.treeWidget_Traits.topLevelItem(17)
        self.trWItem_layer_mass = self.treeWidget_Traits.topLevelItem(18)
        self.trWItem_lmchild_Area = self.trWItem_layer_mass.child(0)
        self.trWItem_lmchild_Length = self.trWItem_layer_mass.child(1)
        self.trWItem_lmchild_Convex_hull = self.trWItem_layer_mass.child(2)
        self.trWItem_lmchild_A_C = self.trWItem_layer_mass.child(3)
        self.trWItem_lmchild_A_L = self.trWItem_layer_mass.child(4)
        self.trWItem_lmchild_L_C = self.trWItem_layer_mass.child(5)
